#!/bin/bash
set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
  echo "Usage: $0 <package-name> [version]"
  exit 1
fi

PKG_NAME="$1"
PKG_VERSION="${2:-0.1.0}"
PKG_DIR="packages/${PKG_NAME}"

if [[ -e "$PKG_DIR" ]]; then
  echo "Error: $PKG_DIR already exists"
  exit 1
fi

mkdir -p "$PKG_DIR"

cat > "$PKG_DIR/package.conf" <<CONF
NAME=${PKG_NAME}
VERSION=${PKG_VERSION}
RELEASE=1
ARCH=x86_64
SOURCE_URL=https://example.com/${PKG_NAME}-${PKG_VERSION}.tar.gz
CHECKSUM=SKIP
DEPENDS=()
BUILD_DEPENDS=()
CONF

cat > "$PKG_DIR/build.sh" <<'BUILD'
#!/bin/bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# shellcheck disable=SC1091
source "$SCRIPT_DIR/package.conf"

WORKDIR="${WORKDIR:-$PWD/work}"
OUTDIR="${OUTDIR:-$PWD/out}"
SRC_ARCHIVE="${WORKDIR}/${NAME}-${VERSION}.tar.gz"
SRC_DIR="${WORKDIR}/${NAME}-${VERSION}"
PKG_ROOT="${WORKDIR}/pkgroot"

mkdir -p "$WORKDIR" "$OUTDIR"

if [[ ! -f "$SRC_ARCHIVE" ]]; then
  echo "Download source archive: $SOURCE_URL"
  wget -O "$SRC_ARCHIVE" "$SOURCE_URL"
fi

if [[ "$CHECKSUM" != "SKIP" ]]; then
  echo "$CHECKSUM  $SRC_ARCHIVE" | sha256sum -c
fi

rm -rf "$SRC_DIR" "$PKG_ROOT"
mkdir -p "$PKG_ROOT"
tar -xf "$SRC_ARCHIVE" -C "$WORKDIR"

cd "$SRC_DIR"
./configure --prefix=/usr
make
make DESTDIR="$PKG_ROOT" install

PACKAGE_FILE="${OUTDIR}/${NAME}-${VERSION}-${RELEASE}-${ARCH}.tar.zst"
tar --zstd -cf "$PACKAGE_FILE" -C "$PKG_ROOT" .

echo "Package created: $PACKAGE_FILE"
BUILD
chmod +x "$PKG_DIR/build.sh"

cat > "$PKG_DIR/README.md" <<DOC
# ${PKG_NAME}

このディレクトリは \

generated by \`./package_new.sh\` です。

## 使い方

1. \`package.conf\` を編集して \`SOURCE_URL\` や依存関係を更新
2. \`build.sh\` 内の build/install ステップをパッケージに合わせて調整
3. \`./build.sh\` を実行して \`out/*.tar.zst\` を生成
DOC

echo "Scaffold created: $PKG_DIR"
